"""Generate arithmetic-cutoff CROSSING tours: N frames whose zoom sweeps a band straddling one of
Fractadyne's render-mode cutoffs, at a fixed hard center, so the arithmetic switch happens mid-run.

The cutoffs (RenderMode::select, tunables.rs):
  * direct -> df32 perturbation  at magnification 1e4   (Mandelbrot)
  * df32   -> floatexp (mode 2)  at PERT_FE_THRESHOLD = 1e28
  * direct -> perturbation       at PERT_JULIA_THRESHOLD = 1e2 (Julia)
  * the f64 magnitude edge near 1e308 (historically a NaN-guard danger zone)

Each tour is one frame per keyframe (fps=1, hold=1), like bench-kit/zoom-seq.py, so
`--render-tour` produces exactly `frames` images on the band. Zoom is written as a mantissa with an
INTEGER exponent (e.g. 3.16e27), never a fractional exponent: Fraktaler-3 3.1 silently falls back to
its persisted session on a fractional exponent, and this generator feeds the cross-renderer lane too.

Centers come from committed data (bench-kit/scenes/*.kfr) so the tours are reproducible from a clean
clone. Output goes to tours/crossing/ by default.

Usage:
  python bench-kit/tools/gen-crossing-tours.py [--frames 60] [--size 3840x2160] [--out tours/crossing]
"""
import argparse
import os
from decimal import Decimal, getcontext

getcontext().prec = 80  # mantissa precision for the zoom literals (centers are copied verbatim)

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
KFR_DIRS = [os.path.join(REPO, "bench-kit", "scenes"),
            os.path.join(REPO, "validation", "corpus", "locations")]


def read_kfr(slug):
    """Return (re, im) strings from a committed .kfr file (searches the known kfr dirs)."""
    for d in KFR_DIRS:
        p = os.path.join(d, slug + ".kfr")
        if os.path.exists(p):
            out = {}
            with open(p) as f:
                for line in f:
                    if ":" in line:
                        k, v = line.split(":", 1)
                        out[k.strip()] = v.strip()
            return out["Re"], out["Im"]
    raise FileNotFoundError(slug + ".kfr not found in " + " or ".join(KFR_DIRS))


def zoom_str(l10, digits=20):
    """A magnification `10**l10` as `<mantissa>e<integer exponent>` (both readers-safe)."""
    e = int(Decimal(l10).to_integral_value(rounding="ROUND_FLOOR"))
    m = Decimal(10) ** (Decimal(l10) - e)  # 1 <= m < 10
    return "%se%d" % (round(m, digits).normalize(), e)


# name -> (re, im, cutoff_log10, band_half_decades, iters, julia, description)
# The band spans [cutoff - half, cutoff + half] decades so the switch lands mid-sequence.
# A seahorse valley point (bench scene 03), precise enough for a 1e2..1e6 band.
SEAHORSE = ("-0.7436438870371587047521915061147707",
            "0.131825904205311970493132056385139")

# id, (re, im), cutoff_log10, half_decades, iters, julia_c or None
# julia_c = (c_re, c_im) turns the tour into a Julia dive; the view re/im is a point IN the set.
TOURS = [
    # direct -> df32 perturbation at 1e4 (Mandelbrot)
    ("seahorse-x1e4",  SEAHORSE,                       4.0,   2.0, 6000,   None),
    # df32 -> floatexp at PERT_FE_THRESHOLD = 1e28 (the two FractalShark-DNF hard locations)
    ("spar-x1e28",     read_kfr("21-m43-spar-1e27.7"), 28.0,  2.0, 200000, None),
    ("nucleus-x1e28",  read_kfr("24-nucleus-p148-1e28.2"), 28.0, 2.0, 200000, None),
    # the f64 magnitude edge near 1e308 (deep floatexp; historically a NaN-guard danger zone)
    ("deep-x1e308",    read_kfr("09-deep-6.1e500"),    308.0, 2.0, 250000, None),
    # direct -> perturbation at PERT_JULIA_THRESHOLD = 1e2, spiral Julia c = -0.8 + 0.156i. The view
    # center is the REPELLING FIXED POINT z- = (1 - sqrt(1-4c)) / 2: the Julia set is self-similar
    # under the map's linear action there, so the band stays a rich picture at every zoom (zooming at
    # the origin instead lands in the exterior and goes flat).
    ("julia-x1e2",     ("-0.5275031186435346", "0.07591217835228786"), 2.0, 2.0, 20000, ("-0.8", "0.156")),
]


def write_tour(path, name, re, im, cutoff, half, frames, size, iters, julia_c, fps=1):
    lo = cutoff - half
    hi = cutoff + half
    lines = [
        "# generated by bench-kit/tools/gen-crossing-tours.py - do not edit by hand",
        "# %d frames sweeping magnification 1e%g -> 1e%g, crossing the cutoff at 1e%g."
        % (frames, lo, hi, cutoff),
        'format_version = 2',
        'name = "%s"' % name,
        '',
        '[render]',
        'size = "%s"' % size,
        'fps = %d' % fps,
        '',
    ]
    for i in range(frames):
        l10 = lo + (hi - lo) * i / (frames - 1)
        lines += ['[[keyframe]]',
                  'id = "f%02d"' % i,
                  't = %d' % i]
        if julia_c is not None:
            # Julia MODE needs the `julia` bool flag; julia_re/julia_im only pin the parameter c.
            # "Julia" is not a `fractal` family. The base family stays Mandelbrot.
            lines += ['julia = true',
                      'julia_re = %s' % julia_c[0],
                      'julia_im = %s' % julia_c[1]]
        lines += ['re = "%s"' % re,
                  'im = "%s"' % im,
                  'zoom = "%s"' % zoom_str(l10),
                  'max_iter = %d' % iters,
                  'hold = 1',
                  '']
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))
    return path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--frames", type=int, default=60)
    ap.add_argument("--size", default="3840x2160")
    ap.add_argument("--out", default=os.path.join(REPO, "tours", "crossing"))
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    for tid, (re, im), cutoff, half, iters, julia_c in TOURS:
        path = os.path.join(a.out, tid + ".toml")
        name = "Cutoff crossing: %s (1e%g band)" % (tid, cutoff)
        write_tour(path, name, re, im, cutoff, half, a.frames, a.size, iters, julia_c)
        print("wrote %s  (%d frames, 1e%g..1e%g, %s)"
              % (os.path.relpath(path, REPO), a.frames, cutoff - half, cutoff + half, a.size))


if __name__ == "__main__":
    main()
