//! Lucide icon glyphs, by name.
//!
//! The UI used Unicode emoji as icons, which had two problems: the bundled fonts cover an
//! arbitrary SUBSET of them (four glyphs shipped as tofu squares before this), and the ones
//! that did render came from different families and did not look like one set.
//!
//! These are Private Use Area codepoints, so they are meaningless on sight - hence names.
//! NEVER write a raw `\u{e...}` escape at a call site; add a constant here instead, and
//! regenerate with `scripts/subset_lucide.py` so the font subset gains the glyph too. A
//! codepoint with no glyph in the subset renders as a blank box, which is the failure mode
//! this module exists to end.
//!
//! Generated by `scripts/subset_lucide.py` - edit the ICONS table there, not this file.
//! Nothing hand-written survives here; the coverage test is in `icons_coverage.rs`.

#![allow(dead_code)] // the full set is deliberately available; not every icon is placed yet

/// Lucide `folder-open` - File > Open view or location, toolbar
pub(crate) const OPEN: &str = "\u{e247}";

/// Lucide `image` - File > Gallery, toolbar
pub(crate) const GALLERY: &str = "\u{e0f6}";

/// Lucide `save` - File > Export image, toolbar
pub(crate) const SAVE: &str = "\u{e14d}";

/// Lucide `camera` - File > Snapshot, toolbar
pub(crate) const SNAPSHOT: &str = "\u{e064}";

/// Lucide `settings` - File > Settings
pub(crate) const SETTINGS: &str = "\u{e154}";

/// Lucide `eraser` - File > Reset application state
pub(crate) const RESET_APP: &str = "\u{e28f}";

/// Lucide `log-out` - File > Quit
pub(crate) const QUIT: &str = "\u{e10e}";

/// Lucide `house` - Navigate > Zoom out to full view, toolbar
pub(crate) const HOME: &str = "\u{e0f5}";

/// Lucide `rotate-ccw` - Navigate > Reset to default view, toolbar
pub(crate) const RESET_VIEW: &str = "\u{e148}";

/// Lucide `dices` - Navigate > Random location
pub(crate) const RANDOM: &str = "\u{e2c5}";

/// Lucide `link` - Navigate > Share location
pub(crate) const SHARE: &str = "\u{e102}";

/// Lucide `zoom-in` - toolbar
pub(crate) const ZOOM_IN: &str = "\u{e1b6}";

/// Lucide `zoom-out` - toolbar
pub(crate) const ZOOM_OUT: &str = "\u{e1b7}";

/// Lucide `crosshair` - toolbar: click-to-zoom toggle
pub(crate) const CLICK_ZOOM: &str = "\u{e0ac}";

/// Lucide `bot` - toolbar: auto-zoom toggle
pub(crate) const AUTOPILOT: &str = "\u{e1bb}";

/// Lucide `palette` - toolbar: next palette
pub(crate) const PALETTE: &str = "\u{e1dd}";

/// Lucide `chart-column` - toolbar: performance panel
pub(crate) const PERF: &str = "\u{e2a3}";

/// Lucide `play` - toolbar + tour transport
pub(crate) const PLAY: &str = "\u{e13c}";

/// Lucide `pause` - tour transport
pub(crate) const PAUSE: &str = "\u{e12e}";

/// Lucide `square` - tour transport
pub(crate) const STOP: &str = "\u{e167}";

/// Lucide `skip-back` - tour transport: restart
pub(crate) const SKIP_BACK: &str = "\u{e15f}";

/// Lucide `rewind` - tour transport: back 10s
pub(crate) const REWIND: &str = "\u{e147}";

/// Lucide `fast-forward` - tour transport: forward 10s
pub(crate) const FORWARD: &str = "\u{e0bd}";

/// Lucide `repeat` - tour transport: loop
pub(crate) const LOOP: &str = "\u{e146}";

/// Lucide `clapperboard` - tour transport: record/tour
pub(crate) const TOUR: &str = "\u{e29b}";

/// Lucide `maximize` - toolbar: fullscreen toggle
pub(crate) const FULLSCREEN: &str = "\u{e112}";

/// Lucide `star` - Navigate > Bookmarks, toolbar
pub(crate) const BOOKMARK: &str = "\u{e176}";

/// Lucide `pencil` - Color > Palette > Custom
pub(crate) const EDIT: &str = "\u{e1f9}";

/// Lucide `x` - tour transport close, gradient stop remove
pub(crate) const CLOSE: &str = "\u{e1b2}";

/// Lucide `plus` - gradient editor: add stop
pub(crate) const ADD: &str = "\u{e13d}";

/// Lucide `trash-2` - bookmarks browser: delete
pub(crate) const DELETE: &str = "\u{e18e}";

/// Lucide `columns-2` - toolbar: dual linked view toggle
pub(crate) const DUAL: &str = "\u{e098}";
