//! Does every character the interface draws have a font that can draw it?
//!
//! Four glyphs shipped as blank squares before this existed; the render gates compare
//! fractal pixels and cannot see a menu. Test-only, but a SEPARATE FILE on purpose:
//! `icons.rs` is generated by `scripts/subset_lucide.py`, which rewrites it whole. This
//! module lived at the bottom of that file until regenerating it for one new icon deleted
//! the check silently - the tests simply stopped existing and the suite still went green.
//! Generated and hand-written code do not share a file.

use std::collections::BTreeSet;

/// The Proportional family as `theme::install_fonts` builds it. Coverage is a union, so the
/// order is documentation rather than logic.
const FONTS: &[(&str, &[u8])] = &[
    ("SplineSans", include_bytes!("../assets/fonts/SplineSans.ttf")),
    ("SplineSansMono", include_bytes!("../assets/fonts/SplineSansMono.ttf")),
    ("Lucide", include_bytes!("../assets/fonts/Lucide.ttf")),
    ("Ubuntu-Light", epaint_default_fonts::UBUNTU_LIGHT),
    ("NotoEmoji", epaint_default_fonts::NOTO_EMOJI_REGULAR),
    ("emoji-icon-font", epaint_default_fonts::EMOJI_ICON),
    ("Hack", epaint_default_fonts::HACK_REGULAR),
];

/// `include_str!` rather than a directory walk, so this works from any working directory and
/// fails to COMPILE if a file is renamed instead of silently scanning less.
const SOURCES: &[(&str, &str)] = &[
    ("menus.rs", include_str!("ui/menus.rs")),
    ("panels.rs", include_str!("ui/panels.rs")),
    ("dialogs.rs", include_str!("ui/dialogs.rs")),
    ("diagnostics.rs", include_str!("ui/diagnostics.rs")),
    ("central.rs", include_str!("ui/central.rs")),
    ("help.rs", include_str!("help.rs")),
    ("icons.rs", include_str!("icons.rs")),
];

fn covered() -> BTreeSet<u32> {
    let mut set = BTreeSet::new();
    for (name, bytes) in FONTS {
        let face = ttf_parser::Face::parse(bytes, 0).unwrap_or_else(|e| panic!("{name}: {e}"));
        for ch in 0u32..=0x10FFFF {
            if let Some(c) = char::from_u32(ch) {
                if face.glyph_index(c).is_some() {
                    set.insert(ch);
                }
            }
        }
    }
    set
}

/// Non-ASCII characters on any line holding a string literal. Deliberately crude: it
/// OVER-collects (a character in a trailing comment counts) rather than under-collects.
/// Over-collecting costs one covered glyph in a list; under-collecting is how a tofu ships.
fn used() -> Vec<(u32, &'static str, usize)> {
    let mut out = Vec::new();
    let mut seen = BTreeSet::new();
    for (file, src) in SOURCES {
        for (n, line) in src.lines().enumerate() {
            if line.trim_start().starts_with("//") || !line.contains('"') {
                continue;
            }
            for ch in line.chars().filter(|c| !c.is_ascii()) {
                if seen.insert(ch as u32) {
                    out.push((ch as u32, *file, n + 1));
                }
            }
        }
    }
    out
}

#[test]
fn every_ui_glyph_has_a_font_that_can_draw_it() {
    let have = covered();
    let want = used();
    assert!(want.len() > 20, "only {} glyphs scanned â€” the scan is broken", want.len());
    let missing: Vec<_> = want.iter().filter(|(cp, _, _)| !have.contains(cp)).collect();
    assert!(
        missing.is_empty(),
        "{} glyph(s) no bundled font can draw â€” each renders as a blank box:\n{}",
        missing.len(),
        missing
            .iter()
            .map(|(cp, f, l)| format!(
                "  U+{cp:04X} {:?} at {f}:{l}",
                char::from_u32(*cp).unwrap_or('?')
            ))
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// The check above is worthless if it cannot fail, and "nothing missing" looks exactly like
/// "the font scan returned everything". This pins both halves.
#[test]
fn the_coverage_check_can_actually_fail() {
    let have = covered();
    assert!(have.len() > 1000, "font scan produced only {} codepoints", have.len());

    // The four that actually shipped as tofu, plus an unassigned codepoint.
    for cp in [0x270Eu32, 0x2713, 0x2715, 0x1F916, 0x10FFFD] {
        assert!(
            !have.contains(&cp),
            "U+{cp:04X} now reports as covered â€” if a font gained it, give this negative \
             control a different codepoint rather than deleting it"
        );
    }
    for cp in [0x2716u32, 0x2714, 0x0041] {
        assert!(have.contains(&cp), "U+{cp:04X} should be covered");
    }
    // A Lucide icon: without this, dropping the subset from the build would blank every icon
    // in the UI and the test above would still pass.
    let bot = crate::icons::AUTOPILOT.chars().next().unwrap() as u32;
    assert!(have.contains(&bot), "the Lucide subset is missing (U+{bot:04X})");
}
