//! Lucide icon glyphs, by name.
//!
//! The UI used Unicode emoji as icons, which had two problems: the bundled fonts cover an
//! arbitrary SUBSET of them (four glyphs shipped as tofu squares before this), and the ones
//! that did render came from different families and did not look like one set.
//!
//! These are Private Use Area codepoints, so they are meaningless on sight - hence names.
//! NEVER write a raw `\u{e...}` escape at a call site; add a constant here instead, and
//! regenerate with `scripts/subset_lucide.py` so the font subset gains the glyph too. A
//! codepoint with no glyph in the subset renders as a blank box, which is the failure mode
//! this module exists to end.
//!
//! Generated by `scripts/subset_lucide.py` - edit the ICONS table there, not this file.

#![allow(dead_code)] // the full set is deliberately available; not every icon is placed yet

/// Lucide `folder-open` - File > Open view or location, toolbar
pub(crate) const OPEN: &str = "\u{e247}";

/// Lucide `image` - File > Gallery, toolbar
pub(crate) const GALLERY: &str = "\u{e0f6}";

/// Lucide `save` - File > Export image, toolbar
pub(crate) const SAVE: &str = "\u{e14d}";

/// Lucide `camera` - File > Snapshot, toolbar
pub(crate) const SNAPSHOT: &str = "\u{e064}";

/// Lucide `settings` - File > Settings
pub(crate) const SETTINGS: &str = "\u{e154}";

/// Lucide `eraser` - File > Reset application state
pub(crate) const RESET_APP: &str = "\u{e28f}";

/// Lucide `log-out` - File > Quit
pub(crate) const QUIT: &str = "\u{e10e}";

/// Lucide `house` - Navigate > Zoom out to full view, toolbar
pub(crate) const HOME: &str = "\u{e0f5}";

/// Lucide `rotate-ccw` - Navigate > Reset to default view, toolbar
pub(crate) const RESET_VIEW: &str = "\u{e148}";

/// Lucide `dices` - Navigate > Random location
pub(crate) const RANDOM: &str = "\u{e2c5}";

/// Lucide `link` - Navigate > Share location
pub(crate) const SHARE: &str = "\u{e102}";

/// Lucide `zoom-in` - toolbar
pub(crate) const ZOOM_IN: &str = "\u{e1b6}";

/// Lucide `zoom-out` - toolbar
pub(crate) const ZOOM_OUT: &str = "\u{e1b7}";

/// Lucide `crosshair` - toolbar: click-to-zoom toggle
pub(crate) const CLICK_ZOOM: &str = "\u{e0ac}";

/// Lucide `bot` - toolbar: auto-zoom toggle
pub(crate) const AUTOPILOT: &str = "\u{e1bb}";

/// Lucide `palette` - toolbar: next palette
pub(crate) const PALETTE: &str = "\u{e1dd}";

/// Lucide `chart-column` - toolbar: performance panel
pub(crate) const PERF: &str = "\u{e2a3}";

/// Lucide `play` - toolbar + tour transport
pub(crate) const PLAY: &str = "\u{e13c}";

/// Lucide `pause` - tour transport
pub(crate) const PAUSE: &str = "\u{e12e}";

/// Lucide `square` - tour transport
pub(crate) const STOP: &str = "\u{e167}";

/// Lucide `skip-back` - tour transport: restart
pub(crate) const SKIP_BACK: &str = "\u{e15f}";

/// Lucide `rewind` - tour transport: back 10s
pub(crate) const REWIND: &str = "\u{e147}";

/// Lucide `fast-forward` - tour transport: forward 10s
pub(crate) const FORWARD: &str = "\u{e0bd}";

/// Lucide `repeat` - tour transport: loop
pub(crate) const LOOP: &str = "\u{e146}";

/// Lucide `clapperboard` - tour transport: record/tour
pub(crate) const TOUR: &str = "\u{e29b}";

/// Lucide `maximize` - toolbar: fullscreen toggle
pub(crate) const FULLSCREEN: &str = "\u{e112}";

/// Lucide `star` - Navigate > Bookmarks, toolbar
pub(crate) const BOOKMARK: &str = "\u{e176}";

/// Lucide `pencil` - Color > Palette > Custom
pub(crate) const EDIT: &str = "\u{e1f9}";

/// Lucide `x` - tour transport close, gradient stop remove
pub(crate) const CLOSE: &str = "\u{e1b2}";

/// Lucide `plus` - gradient editor: add stop
pub(crate) const ADD: &str = "\u{e13d}";

/// Lucide `trash-2` - bookmarks browser: delete
pub(crate) const DELETE: &str = "\u{e18e}";

/// Guard: every glyph the UI draws must exist in a font the app actually loads.
///
/// A codepoint no loaded font covers renders as a blank box, and that is invisible to every other
/// gate here — the render tests compare fractal pixels and `--uitest` writes screenshots for a
/// human — so four tofu glyphs shipped and reached a manual review. Two were only reachable in
/// states a reviewer had to stumble into: a check mark that appears in the deep-zoom budget
/// readout once it settles, and an X in the gradient editor with three or more stops.
///
/// Every miss was ONE codepoint away from something that works (`U+2716` heavy-x is covered while
/// `U+2715` is not; `U+2714` heavy-check is covered while `U+2713` is not), so it is not the kind
/// of mistake care avoids. This makes it impossible instead.
#[cfg(test)]
mod coverage {
    use std::collections::BTreeSet;

    /// The Proportional family as `theme::install_fonts` builds it. Coverage is a union, so the
    /// order is documentation rather than logic.
    const FONTS: &[(&str, &[u8])] = &[
        ("SplineSans", include_bytes!("../assets/fonts/SplineSans.ttf")),
        ("SplineSansMono", include_bytes!("../assets/fonts/SplineSansMono.ttf")),
        ("Lucide", include_bytes!("../assets/fonts/Lucide.ttf")),
        ("Ubuntu-Light", epaint_default_fonts::UBUNTU_LIGHT),
        ("NotoEmoji", epaint_default_fonts::NOTO_EMOJI_REGULAR),
        ("emoji-icon-font", epaint_default_fonts::EMOJI_ICON),
        ("Hack", epaint_default_fonts::HACK_REGULAR),
    ];

    /// `include_str!` rather than a directory walk, so this works from any working directory and
    /// fails to COMPILE if a file is renamed instead of silently scanning less.
    const SOURCES: &[(&str, &str)] = &[
        ("menus.rs", include_str!("ui/menus.rs")),
        ("panels.rs", include_str!("ui/panels.rs")),
        ("dialogs.rs", include_str!("ui/dialogs.rs")),
        ("diagnostics.rs", include_str!("ui/diagnostics.rs")),
        ("central.rs", include_str!("ui/central.rs")),
        ("help.rs", include_str!("help.rs")),
        ("icons.rs", include_str!("icons.rs")),
    ];

    fn covered() -> BTreeSet<u32> {
        let mut set = BTreeSet::new();
        for (name, bytes) in FONTS {
            let face = ttf_parser::Face::parse(bytes, 0).unwrap_or_else(|e| panic!("{name}: {e}"));
            for ch in 0u32..=0x10FFFF {
                if let Some(c) = char::from_u32(ch) {
                    if face.glyph_index(c).is_some() {
                        set.insert(ch);
                    }
                }
            }
        }
        set
    }

    /// Non-ASCII characters on any line holding a string literal. Deliberately crude: it
    /// OVER-collects (a character in a trailing comment counts) rather than under-collects.
    /// Over-collecting costs one covered glyph in a list; under-collecting is how a tofu ships.
    fn used() -> Vec<(u32, &'static str, usize)> {
        let mut out = Vec::new();
        let mut seen = BTreeSet::new();
        for (file, src) in SOURCES {
            for (n, line) in src.lines().enumerate() {
                if line.trim_start().starts_with("//") || !line.contains('"') {
                    continue;
                }
                for ch in line.chars().filter(|c| !c.is_ascii()) {
                    if seen.insert(ch as u32) {
                        out.push((ch as u32, *file, n + 1));
                    }
                }
            }
        }
        out
    }

    #[test]
    fn every_ui_glyph_has_a_font_that_can_draw_it() {
        let have = covered();
        let want = used();
        assert!(want.len() > 20, "only {} glyphs scanned — the scan is broken", want.len());
        let missing: Vec<_> = want.iter().filter(|(cp, _, _)| !have.contains(cp)).collect();
        assert!(
            missing.is_empty(),
            "{} glyph(s) no bundled font can draw — each renders as a blank box:\n{}",
            missing.len(),
            missing
                .iter()
                .map(|(cp, f, l)| format!(
                    "  U+{cp:04X} {:?} at {f}:{l}",
                    char::from_u32(*cp).unwrap_or('?')
                ))
                .collect::<Vec<_>>()
                .join("\n")
        );
    }

    /// The check above is worthless if it cannot fail, and "nothing missing" looks exactly like
    /// "the font scan returned everything". This pins both halves.
    #[test]
    fn the_coverage_check_can_actually_fail() {
        let have = covered();
        assert!(have.len() > 1000, "font scan produced only {} codepoints", have.len());

        // The four that actually shipped as tofu, plus an unassigned codepoint.
        for cp in [0x270Eu32, 0x2713, 0x2715, 0x1F916, 0x10FFFD] {
            assert!(
                !have.contains(&cp),
                "U+{cp:04X} now reports as covered — if a font gained it, give this negative \
                 control a different codepoint rather than deleting it"
            );
        }
        for cp in [0x2716u32, 0x2714, 0x0041] {
            assert!(have.contains(&cp), "U+{cp:04X} should be covered");
        }
        // A Lucide icon: without this, dropping the subset from the build would blank every icon
        // in the UI and the test above would still pass.
        let bot = super::AUTOPILOT.chars().next().unwrap() as u32;
        assert!(have.contains(&bot), "the Lucide subset is missing (U+{bot:04X})");
    }
}
