#!/usr/bin/env python3
"""Regenerate the open-items index at the top of TODO.md, and optionally export a dated
.xlsx snapshot.

    python scripts/todo_index.py            # rewrite the index block in TODO.md
    python scripts/todo_index.py --xlsx     # also write local/todo-snapshot-YYYY-MM-DD.xlsx

TODO.md stays the single source of truth: the index is a generated VIEW between the
TODO-INDEX markers (everything between them is overwritten on each run), and the snapshot is
a dated report in the gitignored local/ folder, never a second tracker. Run this whenever
items are added, closed, or re-prioritized.
"""

import argparse
import datetime
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TODO = ROOT / "TODO.md"
BEGIN = "<!-- TODO-INDEX:BEGIN — generated by scripts/todo_index.py; do not edit by hand -->"
END = "<!-- TODO-INDEX:END -->"

PRIORITY_ORDER = {"\U0001f534": 0, "\U0001f7e0": 1, "\U0001f7e1": 2, "\U0001f7e2": 3}
PRIORITY_NAME = {0: "red", 1: "orange", 2: "yellow", 3: "green", 4: "-"}


def clean_title(raw: str) -> str:
    t = raw
    # strip the checkbox, bold markers, and leading emphasis emoji (kept as columns instead)
    t = re.sub(r"^\s*-\s*\[\s\]\s*", "", t)
    t = t.replace("**", "")
    t = re.sub(r"^[\U0001f534\U0001f7e0\U0001f7e1\U0001f7e2⭐⚠\U0001f4d0\s]+", "", t)
    t = t.strip()
    # one line only; mark continuation when the source line wraps mid-sentence
    if len(t) > 110:
        t = t[:107].rstrip() + "…"
    elif not re.search(r"[.!?)…]\s*$", t):
        t += " …"
    return t


def parse_items():
    lines = TODO.read_text(encoding="utf-8").splitlines()
    items = []
    section = ""
    in_index = False
    for i, line in enumerate(lines, 1):
        if line.startswith(BEGIN):
            in_index = True
            continue
        if line.startswith(END):
            in_index = False
            continue
        if in_index:
            continue
        if line.startswith("## ") or line.startswith("# "):
            section = line.lstrip("#").strip()
            # keep section names short in the table
            section = re.sub(r"\s*[—-]\s*(TRIAGE|SHIPPED|v0\.2).*$", "", section).strip()
            continue
        if re.match(r"^\s{0,4}- \[ \]", line):
            prio = 4
            for mark, order in PRIORITY_ORDER.items():
                if mark in line:
                    prio = order
                    break
            stars = line.count("⭐")
            items.append(
                {
                    "line": i,
                    "prio": prio,
                    "stars": stars,
                    "title": clean_title(line),
                    "section": section,
                }
            )
    return items


def render_index(items) -> str:
    today = datetime.date.today().isoformat()
    flagged = [x for x in items if x["prio"] < 4 or x["stars"] >= 1]
    tail = [x for x in items if x not in flagged]
    flagged.sort(key=lambda x: (x["prio"], -x["stars"], x["line"]))
    out = [BEGIN]
    out.append(f"## Open-items index ({len(items)} open — regenerated {today})")
    out.append("")
    out.append("A generated VIEW of every unchecked item below; the entries themselves are the")
    out.append("source of truth. Regenerate with `python scripts/todo_index.py` (add `--xlsx`")
    out.append("for a dated spreadsheet snapshot in `local/`). Line numbers are clickable in")
    out.append("most editors; sections are the `##` headings the items live under.")
    out.append("")
    out.append("### Flagged (priority mark or ⭐)")
    out.append("")
    out.append("| Pri | ⭐ | Item | Section | Line |")
    out.append("|-----|----|------|---------|------|")
    for x in flagged:
        out.append(
            f"| {PRIORITY_NAME[x['prio']]} | {x['stars'] or ''} | {x['title']} "
            f"| {x['section']} | {x['line']} |"
        )
    out.append("")
    out.append(f"### Unflagged backlog ({len(tail)})")
    out.append("")
    out.append("| Item | Section | Line |")
    out.append("|------|---------|------|")
    for x in sorted(tail, key=lambda x: x["line"]):
        out.append(f"| {x['title']} | {x['section']} | {x['line']} |")
    out.append(END)
    return "\n".join(out)


def rewrite_todo(items):
    text = TODO.read_text(encoding="utf-8")
    block = render_index(items)
    if BEGIN in text and END in text:
        pre = text[: text.index(BEGIN)]
        post = text[text.index(END) + len(END) :]
        text = pre + block + post
    else:
        # first run: insert after the top-level heading
        lines = text.splitlines(keepends=True)
        assert lines[0].startswith("# ")
        text = lines[0] + "\n" + block + "\n" + "".join(lines[1:])
    with io.open(TODO, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    # Line numbers shift when the index itself changes size, so parse-and-render twice:
    # the second pass sees the final layout and its numbers are exact.
    items2 = parse_items()
    block2 = render_index(items2)
    text = TODO.read_text(encoding="utf-8")
    pre = text[: text.index(BEGIN)]
    post = text[text.index(END) + len(END) :]
    with io.open(TODO, "w", encoding="utf-8", newline="\n") as f:
        f.write(pre + block2 + post)
    return items2


def write_xlsx(items):
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill

    today = datetime.date.today().isoformat()
    out = ROOT / "local" / f"todo-snapshot-{today}.xlsx"
    out.parent.mkdir(exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "Open items"
    ws.append(["Priority", "Stars", "Item", "Section", "TODO.md line"])
    for c in ws[1]:
        c.font = Font(bold=True)
    fills = {
        0: PatternFill("solid", fgColor="F4CCCC"),
        1: PatternFill("solid", fgColor="FCE5CD"),
        2: PatternFill("solid", fgColor="FFF2CC"),
        3: PatternFill("solid", fgColor="D9EAD3"),
    }
    for x in sorted(items, key=lambda x: (x["prio"], -x["stars"], x["line"])):
        ws.append(
            [PRIORITY_NAME[x["prio"]], x["stars"], x["title"], x["section"], x["line"]]
        )
        if x["prio"] in fills:
            for c in ws[ws.max_row]:
                c.fill = fills[x["prio"]]
    widths = [10, 6, 110, 40, 12]
    for col, w in zip("ABCDE", widths):
        ws.column_dimensions[col].width = w
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:E{ws.max_row}"
    meta = wb.create_sheet("About")
    meta.append(["Generated", datetime.datetime.now().isoformat(timespec="seconds")])
    meta.append(["Source", "TODO.md (the authoritative tracker — this file is a snapshot)"])
    meta.append(["Open items", len(items)])
    meta.column_dimensions["A"].width = 14
    meta.column_dimensions["B"].width = 70
    wb.save(out)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--xlsx", action="store_true", help="also write the dated snapshot")
    args = ap.parse_args()
    items = parse_items()
    items = rewrite_todo(items)
    print(f"index regenerated: {len(items)} open items")
    if args.xlsx:
        out = write_xlsx(items)
        print(f"snapshot written: {out}")


if __name__ == "__main__":
    sys.exit(main())
