[location]
real = "-0.743643908041274519886726"
imag = "0.131825923574324509717824"
zoom = "3.900947e12"
[image]
width = 1280
height = 720
subframes = 4
[bailout]
iterations = 60000
maximum_reference_iterations = 60000
maximum_perturb_iterations = 60000
maximum_bla_steps = 8192
escape_radius = 256
[transform]
exponential_map = false
[render]
filename = "04-seahorse-1e12-f3"
save_png = true
